[en]
    languageName = "中文"
    title = "kotarou"
    weight = 1
    hasCJKLanguage = true

    # 在这里定义菜单的翻译 (将 zh-cn 改为 en)
    [[en.menu.main]]
        identifier = "home"
        name = "首页"
        url = "/"
        weight = 1
        [en.menu.main.params]
            icon = "home"

    [[en.menu.main]]
        identifier = "archives"
        name = "归档"
        url = "/archives/"
        weight = 2
        [en.menu.main.params]
            icon = "archives"

    [[en.menu.main]]
        identifier = "search"
        name = "搜索"
        url = "/search/"
        weight = 3
        [en.menu.main.params]
            icon = "search"